name: Publish to PyPI
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
      - name: Install poetry and dependencies
        run: |
          pip install "poetry==1.1.4"
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Lint with black, isort, flake8 and mypy
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy .
      - name: Test with pytest
        run: |
          pytest tests/*.py

  test_pypi_publish:
    needs:
      - build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install poetry and dependencies
        run: |
          pip install "poetry==1.1.4"
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Poetry configure PyPI
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_KEY }}"
      - name: Publish package
        run: poetry publish --build
